volumes:
    postgres_data:
    redis_data:

services:
    app:
        build: .
        depends_on:
            - postgres
            - redis
        ports:
            - ${APP_PORT:-8000}:8000
        env_file:
            - .env_compose

    postgres:
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        ports:
            - ${REDIS_PORT:-6379}:6379
        volumes:
            - redis_data:/data
