"""subscription

Revision ID: 337b7c034f6d
Revises: ff6539c20a9e
Create Date: 2024-11-14 22:11:31.251113

"""

from alembic import op
import sqlalchemy as sa
from app.config.sqla.types import EmbedType
from app.contexts.billing.models import SubscriptionMetadata

# revision identifiers, used by Alembic.
revision = "337b7c034f6d"
down_revision = "ff6539c20a9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions_plans",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("remote_product_id", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("remote_customer_id", sa.Text(), server_default="", nullable=False),
        sa.Column("remote_subscription_id", sa.Text(), server_default="", nullable=False),
        sa.Column("remote_price_id", sa.Text(), server_default="", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("meta", EmbedType(SubscriptionMetadata), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscriptions_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "plan_id"),
    )
    op.create_index(op.f("ix_subscriptions_remote_customer_id"), "subscriptions", ["remote_customer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_remote_customer_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("subscriptions_plans")
    # ### end Alembic commands ###
